CREATE CONSTRAINT well_id IF NOT EXISTS FOR (w:Well) REQUIRE w.well_id IS UNIQUE;
CREATE CONSTRAINT bha_id IF NOT EXISTS FOR (b:BHATool) REQUIRE b.part_number IS UNIQUE;
CREATE CONSTRAINT plan_id IF NOT EXISTS FOR (p:HistoricalPlan) REQUIRE p.plan_id IS UNIQUE;
CREATE INDEX formation_name IF NOT EXISTS FOR (f:Formation) ON (f.name);
CREATE CONSTRAINT paper_title IF NOT EXISTS FOR (p:Paper) REQUIRE p.title IS UNIQUE;
CREATE CONSTRAINT topic_name IF NOT EXISTS FOR (t:Topic) REQUIRE t.name IS UNIQUE;
